"""Add unique constraint to watchlist_items

Revision ID: 3824cdd331c2
Revises: c69e1abdd39b
Create Date: 2025-11-10 14:01:13.572639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3824cdd331c2'
down_revision: Union[str, Sequence[str], None] = 'c69e1abdd39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_watchlist_movie', 'watchlist_items', ['watchlist_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlist_movie', 'watchlist_items', type_='unique')
    # ### end Alembic commands ###
